name: Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'bluesky-sandbox'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      shell: bash -l {0}
      run: source continuous_integration/scripts/install.sh
    - name: Build Docs
      run: |
        make -C docs/ html
    - name: Set GITHUB_REPOSITORY_NAME  # just the repo, as opposed to org/repo
      run: echo ${GITHUB_REPOSITORY#*/} >> $GITHUB_RESPOSITORY_NAME
    - name: Deploy documentation to blueskyproject.io.
      # We pin to the SHA, not the tag, for security reasons.
      # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
      uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DOCUMENTATION_DEPLOY_KEY }}
        publish_branch: master
        publish_dir: ./docs/build/html
        external_repository: bluesky-sandbox/bluesky-sandbox.github.io
        destination_dir: ${{ env.GITHUB_REPOSITORY_NAME }}  # just the repo name, without the "bluesky/"
        keep_files: true  # Keep old files.
        force_orphan: false  # Keep git history.
